name: Integration Tests
on: push

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Allow insecure actions commands for setup-haskell add-env
      run: |
        echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

    # Stack is enabled here to prohibit haskell/actions/setup@v1 from updating cabal. 
    # Ref: https://github.com/haskell/actions/blob/main/setup/src/setup-haskell.ts#L49
    - uses: haskell/actions/setup@v1
      id: setup-haskell
      name: Setup ghc/cabal (non-alpine)
      with:
        ghc-version: '8.10.5'
        enable-stack: true 

    - name: Debugging information
      run: |
        ghc --version || echo "no ghc"
        cabal --version || echo "no cabal"
        ghcup --version || echo "no ghcup"

    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-20.09

    - uses: actions/cache@v1
      name: Cache cabal store
      with:
        key: ${{ runner.os }}-cabal-cache-${{ hashFiles('**/*.cabal', '**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-cabal-cache-
          ${{ runner.os }}-
        path: ${{ steps.setup-haskell.outputs.cabal-store || '~/.cabal/store' }}

    # Since spectrometer's distribution does not include required extra-source-files,
    # to successfully build spectrometer test project, mock vendor dependencies.
    - name: Get Spectrometer's vendor dependencies
      run: |
        echo "SPECTROMETERTEST_DIR=`pwd`" >> $GITHUB_ENV
        cabal update || cd "$(dirname "$(find ./dist-newstyle -type f -name spectrometer.cabal | head -1)")" || echo "failed to find spectrometer src package"
        mkdir vendor
        touch vendor/cliv1
        touch vendor/syft
        touch vendor/wiggins 
        cd $SPECTROMETERTEST_DIR

    - name: Build
      run: |
        cabal update
        cabal build

    - name: Run tests
      run: |
        cabal test
