name: Integration Tests
on: push

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-haskell@v1.1
      with:
        ghc-version: '8.8'

    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - uses: actions/cache@v1
      name: Cache cabal store
      with:
        key: ${{ runner.os }}-cabal-cache-${{ hashFiles('**/*.cabal', '**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-cabal-cache-
          ${{ runner.os }}-
        path: ${{ steps.setup-haskell.outputs.cabal-store || '~/.cabal/store' }}

    - name: Build
      run: |
        cabal update
        cabal build

    - name: Run tests
      run: |
        cabal test
